prometheus_config_dir: /opt/prometheus/config
prometheus_rules_dir: "{{ prometheus_config_dir }}/rules"
prometheus_data_dir: /var/lib/prometheus
prometheus_docker_network: monitoring
prometheus_image: "prom/prometheus:latest"
prometheus_listen_address: "0.0.0.0"
prometheus_listen_port: 9090
prometheus_container_uid: 65534
prometheus_container_gid: 65534
prometheus_scrape_host: "{{ certbot_domain | default('task.devops-campus.ru') }}:9090"
prometheus_scrape_jobs:
  - job_name: node
    metrics_path: /metrics
    scheme: https
    targets:
      - "{{ prometheus_scrape_host }}"
  - job_name: bulletins-app
    metrics_path: /actuator/prometheus
    scheme: https
    targets:
      - "{{ prometheus_scrape_host }}"
prometheus_firewall_allowed_tcp_ports: "{{ monitoring_firewall_allowed_tcp_ports }}"
