[web_servers]
web ansible_host=138.16.178.207 ansible_user=root

# Monitoring VM: Prometheus, Grafana, Loki
[monitoring]
metrics ansible_host=138.16.187.61 ansible_user=root

# Алиас app → web_servers (две ВМ: app + monitoring)
[app:children]
web_servers
