---
- name: Prepare monitoring server
  hosts: monitoring
  become: true

  vars_files:
    - "{{ playbook_dir }}/../group_vars/web_servers.yml"
    - "{{ playbook_dir }}/../group_vars/monitoring.yml"

  roles:
    - role: geerlingguy.docker
      tags:
        - prepare
        - monitoring
        - prepare_prometheus
        - prepare_grafana
        - prepare_loki
    - role: prometheus
      tags:
        - monitoring
        - prepare_prometheus
    - role: loki
      tags:
        - monitoring
        - prepare_loki
    - role: grafana
      tags:
        - monitoring
        - prepare_grafana
