---
- name: Deploy bulletin board application
  hosts: web_servers
  become: true

  vars_files:
    - "{{ playbook_dir }}/../group_vars/web_servers.yml"

  roles:
    - role: geerlingguy.docker
      tags:
        - prepare
        - deploy
    - role: geerlingguy.nginx
      tags:
        - prepare
        - deploy
        - nginx
    - role: node_exporter
      tags:
        - prepare
        - monitoring
        - node_exporter
    - role: bulletins
      tags:
        - prepare
        - deploy
        - nginx
        - certbot
